In [155]:
import requests
import pandas as pd
import numpy as np
import json
import time

Nesse script, iremos capturar dados faltantes do nosso dataset, como nome fantasia, raz√£o social, ddd1 e telefone1, ddd2 telefone2, dddfax fax, e-mail.

In [ ]:
dataset = pd.read_csv("condominios_total.csv", dtype=str, encoding='latin1')

In [165]:
dataset = pd.read_csv("condominios_total.csv", dtype=str, encoding='latin1')
dataset.insert(2, 'razao_social', np.nan)
dataset

,cnpj,matriz_filial,razao_social,nome_fantasia,sit_cadast,data_sit_cadast,motivo_sit_cadast,nome_cidade_exterior,pais,data_inicio,...,cep,uf,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email
0,22157373/0001-03,1,NaN,NaN,02,04/09/2014,00,NaN,NaN,04/09/2014,...,60762418,CE,1389,85,88172587,NaN,NaN,85,34892381,EDIFICIOVILLASERENA@GMAIL.COM
1,08448393/0001-02,1,NaN,NaN,02,08/11/2006,00,NaN,NaN,08/11/2006,...,60190750,CE,1389,85,32835360,85,32835360,85,32835360,pmvettor@ig.com.br
2,26073984/0001-24,1,NaN,AR1 SOLUCOES,04,20/03/2019,63,NaN,NaN,30/08/2016,...,60712055,CE,1389,85,98779847,NaN,NaN,NaN,NaN,NaN
3,26130593/0001-02,1,NaN,CONDOMINIO RESIDENCIAL MONTEIRO LOBATO,02,10/06/2016,00,NaN,NaN,10/06/2016,...,60840435,CE,1389,85,32446468,NaN,NaN,NaN,NaN,GERENCIA@BANCODCONDOMINIOS.COM
4,26186449/0001-80,1,NaN,CONDOMINIO RESIDENCIAL CASTRO ALVES,02,23/06/2016,00,NaN,NaN,23/06/2016,...,60872564,CE,1389,85,32446468,NaN,NaN,NaN,NaN,GERENCIA@BANCODECONDOMINIOS.COM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4739,25175204/0001-94,1,NaN,COND MAGNA VILLARIS I,02,09/10/2014,00,NaN,NaN,09/10/2014,...,60873010,CE,1389,85,87037616,NaN,NaN,NaN,NaN,NaN
4740,25303440/0001-49,1,NaN,LIDIAPOLIS CONDOMINIUM,02,03/03/2016,00,NaN,NaN,03/03/2016,...,60160110,CE,1389,85,32580467,NaN,NaN,NaN,NaN,NaN
4741,22064390/0001-04,1,NaN,NaN,02,06/11/2014,00,NaN,NaN,06/11/2014,...,60320380,CE,1389,85,32526485,85,32526486,NaN,NaN,NaN
4742,19640169/0001-34,1,NaN,CONDOMINIO PATIO MESSEJANA,02,12/12/2013,00,NaN,NaN,12/12/2013,...,60872560,CE,1389,85,86702932,85,99949929,NaN,NaN,jurandi_almeida@yahoo.com.br
4743,19756118/0001-72,1,NaN,NaN,02,04/12/2013,00,NaN,NaN,04/12/2013,...,60115220,CE,1389,85,31337000,85,31337002,85,31337010,adm@metaservicos.com.br

In [ ]:
cnpjs_para_consulta = dataset["cnpj"].str.replace('/', '').str.replace('-', '') #removendo / e - dos cnpj para consultar

In [ ]:
for i in range(0, dataset10.shape[0]):
    cnpj = cnpjs_para_consulta[i]
    dados_cnpj = requests.get(f"https://publica.cnpj.ws/cnpj/{cnpj}")
    empresa = dados_cnpj.json()
    empresa

    razao_social = empresa["razao_social"]
    nome_fantasia = empresa["estabelecimento"]["nome_fantasia"]
    ddd1 = empresa["estabelecimento"]["ddd1"]
    telefone1 = empresa["estabelecimento"]["telefone1"]
    ddd2 = empresa["estabelecimento"]["ddd2"]
    telefone2 = empresa["estabelecimento"]["telefone2"]
    ddd_fax = empresa["estabelecimento"]["ddd_fax"]
    fax = empresa["estabelecimento"]["fax"]
    email = empresa["estabelecimento"]["email"]

    try:
        np.isnan(dataset20["razao_social"][i])
        if(razao_social == None):
            pass
        else:
            dataset20["razao_social"][i] = razao_social
    except:
        pass

    try:
        np.isnan(dataset20["nome_fantasia"][i])
        dataset20["nome_fantasia"][i] = nome_fantasia
    except:
        pass

    try:
        np.isnan(dataset20["ddd1"][i])
        dataset20["ddd1"][i] = ddd1
    except:
        pass

    try:
        np.isnan(dataset20["telefone1"][i])
        dataset20["telefone1"][i] = telefone1
    except:
        pass

    try:
        np.isnan(dataset20["ddd2"][i])
        dataset20["ddd2"][i] = ddd2
    except:
        pass

    try:
        np.isnan(dataset20["telefone2"][i])
        dataset20["telefone2"][i] = telefone2
    except:
        pass

    try:
        np.isnan(dataset20["ddd_fax"][i])
        dataset20["ddd_fax"][i] = ddd_fax
    except:
        pass

    try:
        np.isnan(dataset20["fax"][i])
        dataset20["fax"][i] = fax
    except:
        pass

    try:
        np.isnan(dataset20["email"][i])
        dataset20["email"][i] = email
    except:
        pass


    time.sleep(21)

C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:25: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset20["nome_fantasia"][i] = nome_fantasia
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset20["nome_fantasia"][i] = nome_fantasia
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:43: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset20["ddd2"][i] = ddd2
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset20["ddd2"][i] = ddd2
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:49: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset20["telefone2"][i] = telefone2
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset20["telefone2"][i] = telefone2
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:55: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset20["ddd_fax"][i] = ddd_fax
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset20["ddd_fax"][i] = ddd_fax
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:61: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset20["fax"][i] = fax
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset20["fax"][i] = fax
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:67: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset20["email"][i] = email
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\3568772920.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset20["email"][i] = email

In [219]:
dataset10

,cnpj,matriz_filial,nome_fantasia,sit_cadast,data_sit_cadast,motivo_sit_cadast,nome_cidade_exterior,pais,data_inicio,cnae_principal,...,cep,uf,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email
0,22157373/0001-03,1,None,02,04/09/2014,00,NaN,NaN,04/09/2014,8112500,...,60762418,CE,1389,85,88172587,None,None,85,34892381,EDIFICIOVILLASERENA@GMAIL.COM
1,08448393/0001-02,1,None,02,08/11/2006,00,NaN,NaN,08/11/2006,8112500,...,60190750,CE,1389,85,32835360,85,32835360,85,32835360,pmvettor@ig.com.br
2,26073984/0001-24,1,AR1 SOLUCOES,04,20/03/2019,63,NaN,NaN,30/08/2016,8112500,...,60712055,CE,1389,85,98779847,None,None,None,None,None
3,26130593/0001-02,1,CONDOMINIO RESIDENCIAL MONTEIRO LOBATO,02,10/06/2016,00,NaN,NaN,10/06/2016,8112500,...,60840435,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODCONDOMINIOS.COM
4,26186449/0001-80,1,CONDOMINIO RESIDENCIAL CASTRO ALVES,02,23/06/2016,00,NaN,NaN,23/06/2016,8112500,...,60872564,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODECONDOMINIOS.COM
5,26314613/0001-97,1,None,02,10/11/2015,00,NaN,NaN,10/11/2015,8112500,...,60180476,CE,1389,85,34570326,85,34570301,85,34570300,IMPLANTACAO01.COND@GRUPOVIPER.COM.BR
6,27492212/0001-90,1,None,02,12/07/2016,00,NaN,NaN,12/07/2016,8112500,...,60192050,CE,1389,85,31337000,85,31337037,None,None,ADM@METASSERVICOS.COM.BR
7,27799887/0001-86,1,RESIDENCIAL RIACHO VERDE II,02,20/12/2016,00,NaN,NaN,20/12/2016,8112500,...,60732555,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODECONDOMINIOS.COM
8,27808198/0001-90,1,CONDOMINIO HARMONIA,02,18/04/2017,00,NaN,NaN,18/04/2017,8112500,...,60115170,CE,1389,85,33123333,None,None,85,33123333,None
9,29265036/0001-89,1,SERENITA RESIDENCE,02,01/12/2017,00,NaN,NaN,01/12/2017,8112500,...,60192115,CE,1389,85,30999317,85,30999318,None,None,FINANANCEIRO.ADM@ATITUDEGRUPO.COM.BR

### Testes e exports para teste

In [169]:
dataset20 = dataset[:20]
dataset20.to_csv('./comparativo/dataset_original_20_registros.csv', index=False, encoding='latin1')

In [194]:
dataset20.to_csv('./comparativo/dataset_incrementado_20_registros.csv', index=False, encoding='latin1')

In [212]:
dataset

,cnpj,matriz_filial,razao_social,nome_fantasia,sit_cadast,data_sit_cadast,motivo_sit_cadast,nome_cidade_exterior,pais,data_inicio,...,cep,uf,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email
0,22157373/0001-03,1,NaN,None,02,04/09/2014,00,NaN,NaN,04/09/2014,...,60762418,CE,1389,85,88172587,None,None,85,34892381,EDIFICIOVILLASERENA@GMAIL.COM
1,08448393/0001-02,1,NaN,None,02,08/11/2006,00,NaN,NaN,08/11/2006,...,60190750,CE,1389,85,32835360,85,32835360,85,32835360,pmvettor@ig.com.br
2,26073984/0001-24,1,NaN,AR1 SOLUCOES,04,20/03/2019,63,NaN,NaN,30/08/2016,...,60712055,CE,1389,85,98779847,None,None,None,None,None
3,26130593/0001-02,1,NaN,CONDOMINIO RESIDENCIAL MONTEIRO LOBATO,02,10/06/2016,00,NaN,NaN,10/06/2016,...,60840435,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODCONDOMINIOS.COM
4,26186449/0001-80,1,NaN,CONDOMINIO RESIDENCIAL CASTRO ALVES,02,23/06/2016,00,NaN,NaN,23/06/2016,...,60872564,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODECONDOMINIOS.COM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4739,25175204/0001-94,1,NaN,COND MAGNA VILLARIS I,02,09/10/2014,00,NaN,NaN,09/10/2014,...,60873010,CE,1389,85,87037616,NaN,NaN,NaN,NaN,NaN
4740,25303440/0001-49,1,NaN,LIDIAPOLIS CONDOMINIUM,02,03/03/2016,00,NaN,NaN,03/03/2016,...,60160110,CE,1389,85,32580467,NaN,NaN,NaN,NaN,NaN
4741,22064390/0001-04,1,NaN,NaN,02,06/11/2014,00,NaN,NaN,06/11/2014,...,60320380,CE,1389,85,32526485,85,32526486,NaN,NaN,NaN
4742,19640169/0001-34,1,NaN,CONDOMINIO PATIO MESSEJANA,02,12/12/2013,00,NaN,NaN,12/12/2013,...,60872560,CE,1389,85,86702932,85,99949929,NaN,NaN,jurandi_almeida@yahoo.com.br
4743,19756118/0001-72,1,NaN,NaN,02,04/12/2013,00,NaN,NaN,04/12/2013,...,60115220,CE,1389,85,31337000,85,31337002,85,31337010,adm@metaservicos.com.br

In [187]:
dataset1 = dataset[:1]

In [190]:
dataset1["razao_social"][0] = "Teste"

C:\Users\User543\AppData\Local\Temp\ipykernel_6508\2234259792.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset1["razao_social"][0] = "Teste"
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\2234259792.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1["razao_social"][0] = "Teste"
C:\Users\User543\AppData\Local\Temp\ipykernel_6508\2234259792.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Teste' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataset1["razao_social"][0] = "Teste"

In [195]:
dataset20

,cnpj,matriz_filial,razao_social,nome_fantasia,sit_cadast,data_sit_cadast,motivo_sit_cadast,nome_cidade_exterior,pais,data_inicio,...,cep,uf,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email
0,22157373/0001-03,1,EDIFICIO VILLA SERENA,None,02,04/09/2014,00,NaN,NaN,04/09/2014,...,60762418,CE,1389,85,88172587,None,None,85,34892381,EDIFICIOVILLASERENA@GMAIL.COM
1,08448393/0001-02,1,CONDOMINIO DO EDIFICIO AKAROA,None,02,08/11/2006,00,NaN,NaN,08/11/2006,...,60190750,CE,1389,85,32835360,85,32835360,85,32835360,pmvettor@ig.com.br
2,26073984/0001-24,1,AR1 SOLUCOES E SERVICOS DE PORTARIA LTDA,AR1 SOLUCOES,04,20/03/2019,63,NaN,NaN,30/08/2016,...,60712055,CE,1389,85,98779847,None,None,None,None,None
3,26130593/0001-02,1,CONDOMINIO DO RESIDENCIAL MONTEIRO LOBATO,CONDOMINIO RESIDENCIAL MONTEIRO LOBATO,02,10/06/2016,00,NaN,NaN,10/06/2016,...,60840435,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODCONDOMINIOS.COM
4,26186449/0001-80,1,CONDOMINIO DO RESIDENCIAL CASTRO ALVES,CONDOMINIO RESIDENCIAL CASTRO ALVES,02,23/06/2016,00,NaN,NaN,23/06/2016,...,60872564,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODECONDOMINIOS.COM
5,26314613/0001-97,1,JADE - ALTO DAS DUNAS,None,02,10/11/2015,00,NaN,NaN,10/11/2015,...,60180476,CE,1389,85,34570326,85,34570301,85,34570300,IMPLANTACAO01.COND@GRUPOVIPER.COM.BR
6,27492212/0001-90,1,LA PLACE CONDOMINIUM,None,02,12/07/2016,00,NaN,NaN,12/07/2016,...,60192050,CE,1389,85,31337000,85,31337037,None,None,ADM@METASSERVICOS.COM.BR
7,27799887/0001-86,1,RESIDENCIAL RIACHO VERDE II,RESIDENCIAL RIACHO VERDE II,02,20/12/2016,00,NaN,NaN,20/12/2016,...,60732555,CE,1389,85,32446468,None,None,None,None,GERENCIA@BANCODECONDOMINIOS.COM
8,27808198/0001-90,1,CONDOMINIO HARMONIA,CONDOMINIO HARMONIA,02,18/04/2017,00,NaN,NaN,18/04/2017,...,60115170,CE,1389,85,33123333,None,None,85,33123333,None
9,29265036/0001-89,1,SERENITA RESIDENCE,SERENITA RESIDENCE,02,01/12/2017,00,NaN,NaN,01/12/2017,...,60192115,CE,1389,85,30999317,85,30999318,None,None,FINANANCEIRO.ADM@ATITUDEGRUPO.COM.BR
10,30325218/0001-87,1,MARZZANO PREMIUM RESIDENCE,MARZZANO PREMIUM RESIDENCE,02,26/02/2018,00,NaN,NaN,26/02/2018,...,60191005,CE,1389,85,34570303,85,34570326,85,34570303,IMPLANTACAO01.COND@GRUPOVIPER.COM.BR
11,30436970/0001-03,1,CONDOMINIO MARBELLA HOME CLUB,None,02,01/03/2018,00,NaN,NaN,01/03/2018,...,60110371,CE,1389,85,31334444,None,None,None,None,FINANCEIRO@MAGUIAR.COM.BR
12,30628540/0001-85,1,PARQUE DOS IPES,None,02,20/04/2018,00,NaN,NaN,20/04/2018,...,60355337,CE,1389,85,88534231,None,None,None,None,None
13,30836987/0001-40,1,SOLAR PRACA PORTUGAL,SOLAR PRACA PORTUGAL,02,14/06/2018,00,NaN,NaN,14/06/2018,...,60125160,CE,1389,85,99820046,None,None,None,None,None
14,31207705/0001-08,1,PALLADIUM BUSINESS CENTER,PALLADIUM,02,20/07/2018,00,NaN,NaN,20/07/2018,...,60160250,CE,1389,85,32615068,None,None,None,None,DANIELA@CASTELOBORGES.COM.BR
15,32237880/0001-00,1,CONDOMINIO ABSOLUTO PARQUE DO COCO,CONDOMINIO ABSOLUTO PARQUE DO COCO,02,09/04/2018,00,NaN,NaN,09/04/2018,...,60135640,CE,1389,85,98201341,None,None,85,30811718,CONTABILALCANCE01@GMAIL.COM
16,33639194/0001-29,1,CONDOMINIO TERRACOS DO BOSQUE,None,02,24/04/2019,00,NaN,NaN,24/04/2019,...,60320020,CE,1389,85,33123305,None,None,None,None,None
17,33966686/0001-29,1,CONDOMINIO RESIDENCIAL ROMA,None,02,20/12/2018,00,NaN,NaN,20/12/2018,...,60743840,CE,1389,85,87594493,None,None,None,None,LUSIMARIO@YAHOO.COM.BR
18,34968876/0001-48,1,ABSOLUT CONDOMINIUM,ABSOLUT CONDOMINIUM,02,29/08/2019,00,NaN,NaN,29/08/2019,...,60135270,CE,1389,85,88640560,None,None,None,None,ABSOLUTCONDOMINIUM@GMAIL.COM
19,29587639/0001-05,1,EDIFICIO PROMENADE ALDEOTA,None,02,30/11/2017,00,NaN,NaN,30/11/2017,...,60140120,CE,1389,85,33046868,None,None,None,None,PROMENADEALDEOTA@GMAIL.COM

In [198]:
dataset["nome_fantasia"][0] != None

False

In [211]:
if(dataset["nome_fantasia"][3] != None):
    print("Adicionou nome fantasia")

Adicionou nome fantasia

In [213]:
dataset = pd.read_csv("condominios_total.csv", dtype=str, encoding='latin1')
dataset

,cnpj,matriz_filial,nome_fantasia,sit_cadast,data_sit_cadast,motivo_sit_cadast,nome_cidade_exterior,pais,data_inicio,cnae_principal,...,cep,uf,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email
0,22157373/0001-03,1,NaN,02,04/09/2014,00,NaN,NaN,04/09/2014,8112500,...,60762418,CE,1389,85,88172587,NaN,NaN,85,34892381,EDIFICIOVILLASERENA@GMAIL.COM
1,08448393/0001-02,1,NaN,02,08/11/2006,00,NaN,NaN,08/11/2006,8112500,...,60190750,CE,1389,85,32835360,85,32835360,85,32835360,pmvettor@ig.com.br
2,26073984/0001-24,1,AR1 SOLUCOES,04,20/03/2019,63,NaN,NaN,30/08/2016,8112500,...,60712055,CE,1389,85,98779847,NaN,NaN,NaN,NaN,NaN
3,26130593/0001-02,1,CONDOMINIO RESIDENCIAL MONTEIRO LOBATO,02,10/06/2016,00,NaN,NaN,10/06/2016,8112500,...,60840435,CE,1389,85,32446468,NaN,NaN,NaN,NaN,GERENCIA@BANCODCONDOMINIOS.COM
4,26186449/0001-80,1,CONDOMINIO RESIDENCIAL CASTRO ALVES,02,23/06/2016,00,NaN,NaN,23/06/2016,8112500,...,60872564,CE,1389,85,32446468,NaN,NaN,NaN,NaN,GERENCIA@BANCODECONDOMINIOS.COM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4739,25175204/0001-94,1,COND MAGNA VILLARIS I,02,09/10/2014,00,NaN,NaN,09/10/2014,8112500,...,60873010,CE,1389,85,87037616,NaN,NaN,NaN,NaN,NaN
4740,25303440/0001-49,1,LIDIAPOLIS CONDOMINIUM,02,03/03/2016,00,NaN,NaN,03/03/2016,8112500,...,60160110,CE,1389,85,32580467,NaN,NaN,NaN,NaN,NaN
4741,22064390/0001-04,1,NaN,02,06/11/2014,00,NaN,NaN,06/11/2014,8112500,...,60320380,CE,1389,85,32526485,85,32526486,NaN,NaN,NaN
4742,19640169/0001-34,1,CONDOMINIO PATIO MESSEJANA,02,12/12/2013,00,NaN,NaN,12/12/2013,8112500,...,60872560,CE,1389,85,86702932,85,99949929,NaN,NaN,jurandi_almeida@yahoo.com.br
4743,19756118/0001-72,1,NaN,02,04/12/2013,00,NaN,NaN,04/12/2013,8112500,...,60115220,CE,1389,85,31337000,85,31337002,85,31337010,adm@metaservicos.com.br

In [216]:
dataset10 = dataset[:10]

In [217]:
dataset10

,cnpj,matriz_filial,nome_fantasia,sit_cadast,data_sit_cadast,motivo_sit_cadast,nome_cidade_exterior,pais,data_inicio,cnae_principal,...,cep,uf,municipio,ddd1,telefone1,ddd2,telefone2,ddd_fax,fax,email
0,22157373/0001-03,1,NaN,02,04/09/2014,00,NaN,NaN,04/09/2014,8112500,...,60762418,CE,1389,85,88172587,NaN,NaN,85,34892381,EDIFICIOVILLASERENA@GMAIL.COM
1,08448393/0001-02,1,NaN,02,08/11/2006,00,NaN,NaN,08/11/2006,8112500,...,60190750,CE,1389,85,32835360,85,32835360,85,32835360,pmvettor@ig.com.br
2,26073984/0001-24,1,AR1 SOLUCOES,04,20/03/2019,63,NaN,NaN,30/08/2016,8112500,...,60712055,CE,1389,85,98779847,NaN,NaN,NaN,NaN,NaN
3,26130593/0001-02,1,CONDOMINIO RESIDENCIAL MONTEIRO LOBATO,02,10/06/2016,00,NaN,NaN,10/06/2016,8112500,...,60840435,CE,1389,85,32446468,NaN,NaN,NaN,NaN,GERENCIA@BANCODCONDOMINIOS.COM
4,26186449/0001-80,1,CONDOMINIO RESIDENCIAL CASTRO ALVES,02,23/06/2016,00,NaN,NaN,23/06/2016,8112500,...,60872564,CE,1389,85,32446468,NaN,NaN,NaN,NaN,GERENCIA@BANCODECONDOMINIOS.COM
5,26314613/0001-97,1,NaN,02,10/11/2015,00,NaN,NaN,10/11/2015,8112500,...,60180476,CE,1389,85,34570326,85,34570301,85,34570300,IMPLANTACAO01.COND@GRUPOVIPER.COM.BR
6,27492212/0001-90,1,NaN,02,12/07/2016,00,NaN,NaN,12/07/2016,8112500,...,60192050,CE,1389,85,31337000,85,31337037,NaN,NaN,ADM@METASSERVICOS.COM.BR
7,27799887/0001-86,1,RESIDENCIAL RIACHO VERDE II,02,20/12/2016,00,NaN,NaN,20/12/2016,8112500,...,60732555,CE,1389,85,32446468,NaN,NaN,NaN,NaN,GERENCIA@BANCODECONDOMINIOS.COM
8,27808198/0001-90,1,CONDOMINIO HARMONIA,02,18/04/2017,00,NaN,NaN,18/04/2017,8112500,...,60115170,CE,1389,85,33123333,NaN,NaN,85,33123333,NaN
9,29265036/0001-89,1,SERENITA RESIDENCE,02,01/12/2017,00,NaN,NaN,01/12/2017,8112500,...,60192115,CE,1389,85,30999317,85,30999318,NaN,NaN,FINANANCEIRO.ADM@ATITUDEGRUPO.COM.BR